trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  inputs:
    SonarCloud: Sonar
    organization: 'amarok79-github'
    projectKey: 'Amarok79_Events'
    projectName: Amarok.Events

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Debug --no-incremental'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--no-build'

- task: SonarCloudAnalyze@1

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1

- script: 'git clean -d -x -f'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release --no-incremental'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'bin\lib'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
