name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    steps:
      
      - name: Installing .NET Core 2.1...
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x        

      - name: Installing .NET Core 3.1...
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x        
      
      - name: Getting sources...
        uses: actions/checkout@v2

      - name: Restoring packages...
        run: dotnet restore

      - name: Building Debug...
        run: dotnet build --configuration Debug --no-incremental

      - name: Running tests...
        run: dotnet test --no-build

      - name: Cleaning up...
        run: git clean -d -x -f

      - name: Building Release...
        run: dotnet build --configuration Release --no-incremental

      - name: Uploading NuGet package...
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: bin/lib/*.nupkg
          if-no-files-found: error
